apply plugin: 'java-gradle-plugin'
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'com.palantir.gradle-plugin-testing'

dependencies {
    implementation 'com.palantir.gradle.jdks:gradle-jdks'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.palantir.gradle.utils:platform'

    compileOnly 'org.immutables:value::annotations'
    annotationProcessor 'org.immutables:value'

}

gradlePlugin {
    plugins {
        jdks {
            id = 'com.palantir.jdks.latest'
            displayName = 'Palantir Latest JDK Auto-provisioning Plugin'
            description = 'Configure gradle-jdks with the latest blessed JDKs'
            implementationClass = 'com.palantir.gradle.jdkslatest.LatestJdksPlugin'
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.errorprone.disable 'JavaxInjectOnAbstractMethod'
}

